### ISSUE TITLE
pagespeed-chrome-extension

### ISSUE THREAD

**Issue by KishorThube** [songlibo/pagespeed-chrome-extension#10]
Unfortunately, the PageSpeed Insights extension cannot run because the Native Client plugin is not available. The usual reason for this is your are not running the official Google Chrome such as a Chromium build. Check chrome://plugins/ page to make sure "Native Client" is installed and enabled. If you still get this error message, please file a bug.

Chrome version : Version 48.0.2564.82 Ubuntu 14.04 (64-bit)

**Comment by songlibo** [comment]
Not reproducible. Please re-open if the issue still exists.
