### ISSUE TITLE
Windows 10: Pagespeed module has an error: NaCl module load failed 

### ISSUE THREAD

**Issue by stastka** [songlibo/pagespeed-chrome-extension#11]
I have following error if i start Pagespeed:

> Pagespeed module has an error: NaCl module load failed: The Portable Native Client (pnacl) component is not installed. Please consult chrome://components for more information.
- Chromium Project 51.0.2676.0 (64-bit) on Windows 10 (1511)
- Google Chrome 49.0.2623.87 (64-bit) on Windows 10 (1511)
- pnacl - Version: 0.46.0.4 (chrome://components/)
- Native Client - installed (chrome://plugins/)

**Solution:**
I start Browser "run as Administrator", run one Pagespeed, after i can start analyse without Problem with normal User. 

Dany

**Comment by songlibo** [comment]
Thanks for the solution. Closing this bug now.
