### ISSUE TITLE
error in pagespeed backgroud page

### ISSUE THREAD

**Issue by kartiki** [songlibo/pagespeed-chrome-extension#12]
this is what im getting wen i run pagespeed...

![error](https://cloud.githubusercontent.com/assets/6338067/14226365/c9847ad6-f8fd-11e5-9b94-c4355ae59d0e.JPG)

Pagespeed module has an error: NaCl module load failed: The Portable Native Client (pnacl) component is not installed. Please consult chrome://components for more information.

**Comment by songlibo** [comment]
Thanks for reporting this bug. Can you please post the information in you chrome://components to verify that pnacl is installed.

**Comment by songlibo** [comment]
Dany reported in #11 about the same error, and had a workaround:
Solution:
I start Browser "run as Administrator", run one Pagespeed, after i can start analyse without Problem with normal User.

**Comment by songlibo** [comment]
Close. See the above comment for solution.
