### ISSUE TITLE
Pagespeed module has an error: NaCl module load failed: PnaclCoordinator: Compile stream chunk failed: reply not received from PNaCl translator (it probably crashed)

### ISSUE THREAD

**Issue by china-iamk** [songlibo/pagespeed-chrome-extension#13]
my chrome://version/  is 49.0.2623.112 (正式版本) m （64 位）
![2](https://cloud.githubusercontent.com/assets/5343414/15490495/221d9e46-219b-11e6-9f55-df5ea0a22a1c.png)

**Comment by songlibo** [comment]
There is thread about similar issue on the NaCl discussion group:
https://groups.google.com/d/topic/native-client-discuss/tcoLUE_ttSQ/discussion

Quote from that thread:
> Is it out of disk space? You said it wasn't low on memory. We've seen antiviruses cause issues with Chrome before, does it have one installed? Broken/malicious extensions sometimes also cause issues, though rarely with NaCl, are there any installed? Or maybe it has faulty memory, or a bad Chrome install. It may be worth re-installing Chrome?

Can you please try the above? Thanks.

**Comment by songlibo** [comment]
Close this bug for now. Please re-open if the issue still exists.
