### ISSUE TITLE
Unfortunately, the PageSpeed Insights extension cannot run because the Native Client plugin is not available

### ISSUE THREAD

**Issue by dilkhush** [songlibo/pagespeed-chrome-extension#15]
Unfortunately, the PageSpeed Insights extension cannot run because the Native Client plugin is not available. The usual reason for this is your are not running the official Google Chrome such as a Chromium build. Check chrome://plugins/ page to make sure "Native Client" is installed and enabled. If you still get this error message, please file a bug.

Here are the details about OS and browser
Chromium Version 51.0.2704.79 Ubuntu 14.04 (64-bit)

**Comment by songlibo** [comment]
You are running Chromium, not the official Google Chrome. This is WAI.
