### ISSUE TITLE
Loading PNaCl module 

### ISSUE THREAD

**Issue by chenzeyi** [songlibo/pagespeed-chrome-extension#18]
when the version is 42,it shows the same exception as the other guy above;but in version 53,it shows "Loading PNaCl module ... -1% (Experimental. Loading can be slow for the first time installed or updated.)" and it never finish loading.

**Comment by songlibo** [comment]
Cannot reproduce. Close for now. Please re-open if the issue still exits. And please provide more information when you re-open about your OS, Chrome version, etc. Thanks.
