### ISSUE TITLE
 ReferenceError: FileError is not defined

### ISSUE THREAD

**Issue by kevinandersson** [songlibo/pagespeed-chrome-extension#21]
MacOS 10.11.6 - Chrome Version 54.0.2840.71 (64-bit)

Error in Page Speed panel:
 ReferenceError: FileError is not defined
    at pagespeed.ContentWriter.<anonymous> (chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:1205:10)
    at chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh/pagespeed.js:88:21

Please file a bug at
https://github.com/songlibo/pagespeed-chrome-extension/issues

**Comment by bob85** [comment]
I've same issue come up:screen shot:
![dialog](https://cloud.githubusercontent.com/assets/7943472/20356585/f0c9047e-abf2-11e6-9c68-9c3bc36f79a8.jpg)

**Comment by robertstankevich** [comment]
Same here:
![image](https://cloud.githubusercontent.com/assets/17402887/20378908/d4da476e-aca1-11e6-82bb-740a91799340.png)

**Comment by songlibo** [comment]
Can anyone share the URL that causes this issue? Or is it for all urls?

**Comment by robertstankevich** [comment]
google.com for example:) it's for all URLs.

**Comment by bob85** [comment]
The url was: 
www.ROIOutsourcing.com
but happens with any url I try.

**Comment by songlibo** [comment]
I was not able to get the root cause, but pushed a workaround to silence the errors. Please file a new issue if there are other concerns: e.g., optimized content is not available, etc.
