### ISSUE TITLE
non english rtl language looks is awkward how do i set it to english

### ISSUE THREAD

**Issue by shimondoodkin** [songlibo/pagespeed-chrome-extension#22]

**Comment by songlibo** [comment]
Do settings in the options page work?

![image](https://cloud.githubusercontent.com/assets/470672/22842014/bc5c4848-efa1-11e6-9322-689f1d07e672.png)

**Comment by shimondoodkin** [comment]
the select language settings dosn't work at all

the page speed developer tools tab is like:
the tab titles are in English the layout is right to left and google pages result is in Hebrew

**Comment by songlibo** [comment]
Fixed in v0.0.1.5. Language selection should work now, and Arabic and Hebrew should be shown RTL.
