### ISSUE TITLE
Pagespeed return error: Failed to read the 'localStorage' from property 'Window'. Access denied

### ISSUE THREAD

**Issue by sixmo** [songlibo/pagespeed-chrome-extension#25]
![image](https://cloud.githubusercontent.com/assets/4737607/24140419/4707ab9e-0e20-11e7-977e-79f4daed30e7.png)
I'm not sure when this started, but I encountered the error too before I updated Chorme:
Chrome Version 57.0.2987.110

Sorry for the big image (4K screen...)

**Comment by songlibo** [comment]
You may have this "Block third-party cookies and site data" checkbox is set in Content Settings.

https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document

**Comment by songlibo** [comment]
I am closing this issue. Please reopen if the above did not resolve your issue.

**Comment by sixmo** [comment]
That's true, but by choice. Can you indicate which domains should be whitelisted?

Thanks

**Comment by songlibo** [comment]
chrome-extension://lanlbpjbalfkflkhegagflkgcfklnbnh should be whitelisted.
