### ISSUE TITLE
Erro in Version 65.03298.36 64bits

### ISSUE THREAD

**Issue by ivanteles** [songlibo/pagespeed-chrome-extension#30]
typeerror: date.tolSOString is not a function
pagespeed.js:1076:36
at Array.forEach (anonymous>)
at pagespeed;RespirceAccumulator.onHAR_
pagespeed.js:1074:17

**Comment by songlibo** [comment]
Thanks for reporting this issue. Sorry for the late response. It is fixed now in version 0.0.1.9. I am rolling out the fix.
