### ISSUE TITLE
Error: Message length exceeded maximum allowed length

### ISSUE THREAD

**Issue by fakerLinXiao** [songlibo/pagespeed-chrome-extension#31]
![2018-01-14 12 12 44](https://user-images.githubusercontent.com/25616054/34912787-75565c62-f924-11e7-9b0d-fc8a5f811c8a.png)

**Comment by songlibo** [comment]
Thanks for reporting this issue. This is expected. The page that you were analyzing is too large. If that is your own page, consider reducing the size.
