### ISSUE TITLE
A single domain make the tool hang

### ISSUE THREAD

**Issue by MichaelJen** [songlibo/pagespeed-chrome-extension#32]
I have a problem on a single site, where the pagespeed tool just run and run but never end and get no errors, it just keep running on :
" ⚙ Fetching page HAR..."
The page is a Prestashop [arganista.dk](https://arganista.dk/)

**Comment by JackPu** [comment]
I met the same issue~

**Comment by tobysommer** [comment]
I also encouter this issue (infinite "Fetching page HAR...") but only w/ intranet applications. But it did work before!?

PS: arganista.dk does work here...

**Comment by MichaelJen** [comment]
Strange, it still dont work from here in Thailand and friends i ask in
Denmark, see the same "Fetching page HAR ..."


*Best regards*
Michael Jensen
Seo-specialist


http://a3-seo.dk/  mail: michael@a3-seo.dk

*Phone DK +**45 3698 1033* *TH* +66 8 7449 3870 - Skype: michael.smartsol

199 Moo 12
T. Pon-ngam - Buntharik
Ubon Ratchathani 34230
Thailand

2018-04-20 12:47 GMT+07:00 Tobias Sommer <notifications@github.com>:

**Comment by songlibo** [comment]
I am not able to reproduce this. Can you share the Chrome version and OS version?

**Comment by MichaelJen** [comment]
Just updated to, and your right. Now it works again :-)


*Best regards*
Michael Jensen
Seo-specialist


http://a3-seo.dk/  mail: michael@a3-seo.dk

*Phone DK +**45 3698 1033* *TH* +66 8 7449 3870 - Skype: michael.smartsol

199 Moo 12
T. Pon-ngam - Buntharik
Ubon Ratchathani 34230
Thailand

2018-04-23 13:23 GMT+07:00 Tobias Sommer <notifications@github.com>:
